---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  when: >
    gitlab_package is not defined or
    gitlab_package_dependencies is not defined

- block:
  - include_tasks: gitlab_pre.yml
  - include_tasks: gitlab_install.yml
  tags:
    - gitlab_install

- block: # Configure Gitlab
  - include_tasks: gitlab_search_config.yml
  - include_tasks: gitlab_post.yml
  tags:
    - gitlab_configure
